name: Build and Publish image to Docker Hub
on:
  push:
    branches:
      - master

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: |
          docker build . -t isprashant/demo_flask:latest
      - name: push image to docker hub
        run: |
          docker login -u isprashant -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push isprashant/demo_flask:latest
