name: CI/CD Demo Pipeline

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu:22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: |
          echo "Running tests..."
          python -m unittest discover || echo "No tests found"

      - name: Build Docker image
        run: docker build -t demo-app .

      - name: Deploy to Docker container
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_BASE64 }}
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          scp -P 2222 -i key.pem -o StrictHostKeyChecking=no -r ./app.py deployer@localhost:/app/
          ssh -i key.pem -p 2222 deployer@localhost "sudo systemctl restart ssh || echo 'SSH OK'; pkill -f app.py; nohup python3 /app/app.py &"
     
